spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

coupon:
  lock-key-prefix: 'CRL:'
  count-key-prefix: 'CC:'
  downloaders-key-prefix: 'coupon_downloaders'
  coupon-issuance-queue-key: 'coupon_issuance_queue'