spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful
  tomcat:
    threads:
      max: 750
      min-spare: 200
    accept-count: 8192


coupon:
  lock-key-prefix: 'CRL:'
  count-key-prefix: 'CC:'