spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

coupon:
  issue-queue-key: 'issuable_coupon_queue'
  issue-batch-size: 100